# Site settings
author: BJ Lilley
title: BJ Lilley
header-img: img/home-bg.png
email: bethjeanlilley@gmail.com
copyright_name: BJ Lilley
description: > # this means to ignore newlines until "baseurl:"
  dev.in.training
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  lilleydev

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
